### ISSUE TITLE
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

### ISSUE THREAD

**Issue by marcosx86** [compiz-reloaded/ccsm#14]
When trying to run ccsm, everytime I enable a plugin it puts on console this error.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ccm/Widgets.py", line 1483, in enable_plugin
    if conflict.Resolve ():
  File "/usr/lib/python2.7/dist-packages/ccm/Conflicts.py", line 291, in Resolve
    for conflict in self.Conflicts:
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

```

**Comment by XRevan86** [comment]
Is python-gi-cairo installed?

**Comment by marcosx86** [comment]
Sorry, compiled and installed by my own, ccsm should include it as dependency explicity, perhaps.
