### ISSUE TITLE
Preferences button won't work!

### ISSUE THREAD

**Issue by ABOhiccups** [compiz-reloaded/ccsm#23]
Terminal Message:
```
/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py:49: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
Loading icons...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccm/Pages.py", line 1465, in ShowPreferences
    preferencesPage = PreferencesPage(self.Context)
  File "/usr/lib/python3.6/site-packages/ccm/Pages.py", line 1267, in __init__
    self.PluginListPage = PluginListPage(context)
  File "/usr/lib/python3.6/site-packages/ccm/Pages.py", line 1083, in __init__
    self.UpdateEnabledPluginsList()
  File "/usr/lib/python3.6/site-packages/ccm/Pages.py", line 1133, in UpdateEnabledPluginsList
    self.EnabledPluginsList.append(name)
  File "/usr/lib/python3.6/site-packages/ccm/Widgets.py", line 415, in append
    self.store.set(iter, 0, value)
  File "/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 1033, in set
    _set_lists(args[::2], args[1::2])
  File "/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 1029, in _set_lists
    Gtk.ListStore.set(self, treeiter, columns, values)
AttributeError: type object 'ListStore' has no attribute 'set'
```

**Comment by XRevan86** [comment]
00e8470 should mitigate the issue. It is a regression in PyGObject though.
